# -*- coding: utf-8 -*-
"""Week5_Swathi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZlUJXuHdCE4firTYY4h9AS72iPerK5fP
"""

import pandas as pd
import sqlite3 as sql

conn= sql.connect("/content/sql-murder-mystery.db")

"""Trial check Do not consider the below"""

query="""
SELECT name, g.membership_id,g.check_in_date,g.check_in_time,g.check_out_time
FROM get_fit_now_member
JOIN (
    SELECT *
    FROM get_fit_now_check_in
    WHERE membership_id='90081'
) g ON get_fit_now_member.id=g.membership_id

"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query,conn)

"""Display all the murder cases from the date Jan 15 2018 in the SQL City

"""

murders="""
SELECT *
FROM crime_scene_report
WHERE date='20180115'
AND city='SQL City'
AND type='murder';
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(murders,conn)

murders="""
SELECT *
FROM crime_scene_report
WHERE date='20180115'
AND city='SQL City'
AND type='murder';
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(murders,conn)

"""WITNESS 1 details The person living in the last house of Northwestern Dr

Have ordered by address_number in descending order and limited to one


OUTPUT

    person_id	name	address	license_id	ssn
    14887	Morty Schapiro	4919 Northwestern Dr	118009	111564949
"""

witness_1_details = """
SELECT id as person_id,name, address_number||' '||address_street_name AS address,license_id	,ssn
FROM person
Where address_street_name='Northwestern Dr'
ORDER BY address_number DESC
LIMIT 1

"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(witness_1_details,conn)

"""WITNESS Details two Annabel from Franklin Ave Street

    person_id	name	address	license_id	ssn
	16371	Annabel Miller	103 Franklin Ave	490173	318771143
"""

witness_2_details="""
SELECT id as person_id,name, address_number||' '||address_street_name AS address,license_id	,ssn
FROM person
Where address_street_name='Franklin Ave'
AND name LIKE 'Annabel%';
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(witness_2_details,conn)

"""Witness interviews

Interview of witness 1


"""

witness_1_interviewdetails = """
SELECT id as person_id,name, address_number||' '||address_street_name AS address,license_id	,ssn, i.transcript
FROM person
JOIN (
    SELECT person_id, transcript
    From interview
) i ON person.id=i.person_id
Where address_street_name='Northwestern Dr'
ORDER BY address_number DESC
LIMIT 1

"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(witness_1_interviewdetails,conn)

witness_2_interviewdetails="""
SELECT id as person_id,name, address_number||' '||address_street_name AS address,license_id	,ssn,i.transcript
FROM person
JOIN (
    SELECT person_id, transcript
    From interview
) i ON person.id=i.person_id
Where address_street_name='Franklin Ave'
AND name LIKE 'Annabel%';
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(witness_2_interviewdetails,conn)

"""Checking gym database

FIT NOW Golden members with membership number starting with "48Z" details as specified by Witness 1


    id	person_id	name	membership_start_date	membership_status
	48Z7A	28819	Joe Germuska	20160305	gold
	48Z55	67318	Jeremy Bowers	20160101	gold
"""

gym_database="""
SELECT *
FROM get_fit_now_member
WHERE membership_status='gold'
AND id LIKE '48Z%'
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(gym_database,conn)

"""The data is shorted to two people JOE Germuska and JEREMY Bowers To still contract the data to one person querying based on witness two transcript

"last week on January the 9th"
"""

gym_database="""
SELECT *
FROM get_fit_now_member
JOIN(
    SELECT *
    FROM get_fit_now_check_in
    WHERE check_in_date LIKE 20180109
)
WHERE membership_status='gold'
AND id LIKE '48Z%'

"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(gym_database,conn)

"""Since there are a lot of time they have checked in on January 9th Checking the checkin and check out time of Annabelle Miller with id 90081

"""

gym_database="""
SELECT *
FROM get_fit_now_member
JOIN(
    SELECT *
    FROM get_fit_now_check_in
    WHERE check_in_date LIKE 20180109
    AND check_in_time='1600'
    AND	check_out_time ='1700'
)
WHERE membership_status='gold'
AND id LIKE '48Z%'

"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(gym_database,conn)

"""Getting car detials based on witness two details

"""

query="""
SELECT name,license_id, d.plate_number
FROM person
JOIN(
SELECT *
FROM drivers_license
WHERE plate_number LIKE '%H42W%'
) d ON d.id=person.license_id
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query,conn)

"""SINCE only Jeremy Bowers name matches the plate no that includes 'H42' and thecheck in and check out time matches with the witness 2 and also based on statements of witness 1 I conclude that **JEREMY BOWERS as the KILLER **

Details of THE KILLER "JEREMY BOWERS"
"""

killer="""
SELECT name
FROM person
WHERE name="Jeremy Bowers"
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(killer,conn)

"""Interview statement of Jeremy Bowers

"""

killer_transacript="""
SELECT *
FROM person
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(killer_transacript,conn)

"""Based on his statement it seems tha he has been hired by someoneelse
Details
Height 5'5 to 5'7
Red Hair
Drives Tesla model S
Attended SLA Symphony Concert

"""

event_check="""
SELECT *
FROM facebook_event_checkin
JOIN(
    SELECT name,id
    FROM person
    JOIN (
        SELECT id as license_id FROM
        drivers_license
        WHERE car_make = "Tesla"
        AND car_model = "Model S"
        AND gender = "female"
        AND hair_color = "red"
    )d ON d.license_id=person.license_id
)p ON p.id=facebook_event_checkin.person_id
Where event_name="SQL Symphony Concert"
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(event_check,conn)

"""
    person_id	event_id	event_name	date	name	id
    99716	1143	SQL Symphony Concert	20171206	Miranda Priestly	99716
	99716	1143	SQL Symphony Concert	20171212	Miranda Priestly	99716
	99716	1143	SQL Symphony Concert	20171229	Miranda Priestly	99716

All three records on differenct dates of the concert show the same person MIRANDA PRIESLY thus I conclude that the person hired the murderer is

***MIRANDA PRIESTLY ***"""